name: Terraform Security Scan

on:
  push:  # 모든 브랜치의 모든 푸시에 대해 실행
  pull_request:
    branches: [ main, master ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 pandas scikit-learn requests pyyaml
        
    - name: Install Checkov
      run: |
        pip install checkov
    
    - name: Install tfsec
      run: |
        # 직접 GitHub 릴리스에서 다운로드
        wget -O tfsec https://github.com/aquasecurity/tfsec/releases/download/v1.28.1/tfsec-linux-amd64
        chmod +x tfsec
        sudo mv tfsec /usr/local/bin/
    
    - name: Install Terrascan
      run: |
        # 직접 GitHub 릴리스에서 다운로드
        wget -O terrascan.tar.gz https://github.com/tenable/terrascan/releases/download/v1.18.3/terrascan_1.18.3_Linux_x86_64.tar.gz
        tar -xf terrascan.tar.gz terrascan
        sudo install terrascan /usr/local/bin && rm terrascan terrascan.tar.gz
        
    - name: Check repository structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory structure:"
        ls -la
        
        # examples 디렉토리 확인
        if [ -d "./examples" ]; then
          echo "Examples directory exists"
          ls -la ./examples
        else
          echo "Examples directory not found"
          mkdir -p ./examples/vulnerable
          echo 'Creating dummy file' > ./examples/vulnerable/main.tf
        fi
        
    - name: Create scan results directory
      run: mkdir -p scan_results
        
    - name: Run security scan
      id: security_scan
      run: |
        # 모의 스캔 실행
        SCAN_OUTPUT=$(python run_security_scan.py --dir ./examples/vulnerable --mock)
        
        # 결과에서 취약점 확인
        if echo "$SCAN_OUTPUT" | grep -q "심각한 취약점"; then
          echo "::warning::심각한 보안 취약점이 발견되었습니다!"
          echo "::set-output name=has_critical::true"
        else
          echo "::set-output name=has_critical::false"
        fi
        
    - name: Check deployment status
      run: echo "Security scan completed"
        
    - name: Fail if critical vulnerabilities found
      if: steps.security_scan.outputs.has_critical == 'true'
      run: |
        echo "심각한 취약점이 발견되어 파이프라인이 중단되었습니다!"
        exit 1